from bs4 import BeautifulSoup
import pandas as pd
import os,re
import requests
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3029.110 Safari/537.3'}

urls = [ 'https://www.menugordonjones.co.uk/','https://www.raphaelrestaurant.co.uk','https://www.bathenhouse.co.uk/dining','https://www.bathenhouse.co.uk/dining',
    'https://www.thegainsboroughbathspa.co.uk','https://www.thecircusrestaurant.co.uk/','https://www.hudsonsteakhouse.co.uk/','https://www.chequersbath.net/ ',
    'https://www.henrysrestaurantbath.com/','https://www.woodsrestaurant.com/' ,'https://www.theherdrestaurant.co.uk/','https://www.claytonskitchen.com/',
    'https://www.jarsmeze.com/' ,'https://www.bathwickboatman.com/  ','https://www.olivetreebath.co.uk/ ','https://www.noyaskitchen.co.uk/ ' ,
    'https://www.chezdominique.co.uk/ ','https://www.anticabath.co.uk/ ','https://www.doughpizzarestaurant.co.uk/ ','https://www.royalcrescent.co.uk',
    'https://www.firehouserotisserie.co.uk/ ','https://www.theivybathbrasserie.com/ ','https://www.opabath.com/ ','https://www.taginezhor.co.uk/' ,'https://www.theravenofbath.co.uk/ ',
    'https://www.la-perla.co.uk/ ','https://www.theovenpizzeria.co.uk/','https://www.rusticobistroitaliano.co.uk/ ','https://www.pontevecchiobath.com/ ' ,
    'https://www.thescallopshell.co.uk/ ','https://www.martinirestaurant.co.uk/ ','https://www.eightinbath.co.uk/ ','https://www.thepumproombath.co.uk/' ,
    'https://www.cominstea.com/ ','https://www.cote.co.uk/restaurant/bath/#','https://www.bills-website.co.uk/restaurants/bath ','https://www.joyarestaurant.co.uk/',
    'https://www.oletapas.co.uk/','https://www.oakrestaurant.co.uk/','https://www.pintxobath.co.uk/','https://www.nourishbath.co.uk/' ,'https://www.thelocksbrookinn.com/ ',
    'https://www.aqua-restaurant.com/','https://www.yakyetiyak.co.uk/ ','https://www.corkagebath.com/chapel-row-bath/ ','https://www.hareandhoundsbath.com/  ',
    'https://www.comptoirpluscuisine.com/','https://www.realitalianpizza.co.uk/' ,'https://www.amaroneristorante.co.uk/ ','https://www.hall-woodhousebath.co.uk',
    'https://www.restaurantwebexperts.com/ChaiWalla/','https://www.bathpizzaco.com/','https://www.crystalpalacepub.co.uk/ ','https://www.thecork.co.uk/  ',
    'https://www.pubswithmore.co.uk/canonbath  ','https://www.salamanderbath.co.uk/  ','https://www.thehoppolebath.co.uk/  ','https://www.dianascafe.co.uk/bath/ ',
    'https://www.thecurfewbath.co.uk/index ' ,'https://www.thebellinnbath.co.uk/ ','https://www.greatukpubs.co.uk/lambandlionbath  ',
    'https://www.butcombe.com/pig-and-fiddle/  ','https://www.marlborough-tavern.com/ ','https://www.victoriabath.co.uk/  ','https://www.rootedcafe.co.uk/ ',
    'https://www.roseandcrownlarkhall.co.uk','https://www.thebathamptonmill.co.uk/ '  'https://www.bostonteaparty.co.uk/  ' ,'https://www.thegrocercafe.co.uk/ ',
    'https://www.greenbirdcafe.co.uk/  ','https://www.cafelucca.co.uk/ ','https://www.gooddaycoffee.co.uk/','https://www.mokokocoffee.com/  ' ,
    'https://www.lulucaffe.co.uk/  ','https://www.caferetro.co.uk/ ','https://www.adventurecafebar.co.uk/ ','https://www.cafeaulait.co.uk/  ' ,'https://www.foxandkitcafe.com/',
    'https://www.theprovenist.com/ ','https://www.bathmamak.co.uk/ ','https://www.ruposhitakeaway.co.uk/  ','https://www.kushbubath.co.uk/ ','https://www.taka-taka.co.uk/ ',
    'https://www.cheongsing.com/ ','https://www.bathfishandchips.co.uk/ ','https://www.beargrillsbath.co.uk/ '
]
images = []

for url in urls:
    source = requests.get(url, headers = headers).text
    soup  = BeautifulSoup(source , 'html.parser')
    #print(soup.prettify())

    for img in soup.find_all('img',{'src': re.compile('^https://')}):
        imgs= img.attrs.get('src')
        #print(jpg+'\n')
        images.append(imgs)

print('\n\n' .join(map(str,images) ) )
#print(len(images))

os.mkdir('photos')
i = 1

for index, img_link in enumerate(images):
    if i<=786:
        img_data = requests.get(img_link).content
        with open('photos/'+str(index+1), 'wb+') as file:
            file.write(img_data)
        i +=1
    else:
        file.close()
        break




[
'https://www.no15greatpulteney.co.uk/',
'https://www.nilviphotelsgroup.com/  ',
'https://www.thebathpriory.co.uk/    ',
'https://www.edgar-townhouse.co.uk/  ',
'https://www.pulteneyhotel.co.uk/    ',
'https://www.brooksguesthouse.com/   ',
'https://www.thequeensberry.co.uk/   ',
'https://www.handpickedhotels.co.uk/bailbrookhouse/ ',
'https://www.thebirdbath.co.uk/'    ,
'https://www.dukesbath.co.uk/'    ,
'https://www.francishotel.com/'    ,
'https://www.bathenhouse.co.uk/'    ,
'https://www.poplarhousebath.com/'  ,
'https://www.bath-narrowboats.co.uk/',
'https://www.lamppostvilla.co.uk/'   ,
'https://www.nilviphotelsgroup.com/paradepark/index.asp/',
'https://www.bathguesthouse.com/   ',
'https://www.marlborough-house.net/',
'https://www.thehenry.com/         ',
'https://www.brooksguesthouse.com/ ',
'https://www.waterhousebath.co.uk/ ',
'https://www.kennard.co.uk/        ',
'https://www.bathwindsorguesthouse.com/ ',
'https://www.ayrlington.com/         ',
'https://www.graysbath.co.uk/        ',
'https://www.2crescentgardens.co.uk/ ',
'https://www.hillhousebath.co.uk/    ',
'https://www.brindleysbath.co.uk/    ',
'https://www.boathouse-bath.co.uk/   ',
'https://www.dorianhouse.co.uk/      ',
'https://www.chestnutshouse.co.uk/   ',
'https://www.blackfoxbath.com/       ',
'https://www.brocksguesthouse.co.uk/ ',
'https://www.thenewcrowninn.co.uk/   ',
'https://www.devonshire-house.uk.com/      ',
'https://www.bodhihouse.co.uk/             ',
'https://www.cranleighbath.com/            ',
'https://www.ecobloomfield.com/            ',
'https://www.grosvenorvillabath.co.uk/     ',
'https://www.anabellesguesthouse.co.uk/    ',
'https://www.cornerwaysbath.co.uk/         ',
'https://www.bathfarmcottages.co.uk/       ',
'https://www.simplybathholidayrentals.com/ ',
'https://www.holidaycottagebath.co.uk/     ',
'https://circleluxurystays.co.uk/          ',
'https://www.abbeymewsbath.co.uk/          ',
'https://www.pandasanctuaries.com/         ',
'https://www.hopeplacebath.co.uk/          ',
'https://www.bathapartmentbreaks.co.uk/ ',
'https://www.superiorproperties.co.uk/  ',
'https://www.wentworthhouse.co.uk/      ',
'https://www.hidingspace.co.uk/         ',
'https://www.roseatehotels.com/bath/theroseatevilla/',
'https://www.therisingsunbath.co.uk/  ',
'https://www.tyndallvilla.co.uk/      ',
'https://www.limpleystokehotel.co.uk/ ',
'https://www.ymcabath.org.uk/         ',
'https://www.elginvilla.co.uk/        ',
'https://www.appletreeguesthouse.com/ ',
'https://www.tasburghhouse.co.uk/     ',
'https://www.yha.org.uk/              ',
'https://www.marishasinbath.com/      ',
'https://www.62gps.co.uk/             ',
'https://www.theholliesbath.co.uk/    ',
'https://www.combegrove.com/          ',
'https://www.belmontbath.co.uk/       ',
'https://www.bridgehousebath.co.uk/   ',
'https://www.memblandguesthouse.co.uk/',
'https://www.bathselfcatering.net/    ',
'https://www.rainbowwoodfarm.com/     ',
'https://www.thecoachhousebath.co.uk/ ',
'https://www.thecuratorsapartment.com/',
'https://www.zenhousebath.co.uk/      ',
'https://www.pennsylvaniafarm.co.uk/  ',
'https://www.ba1hair.co.uk/           ',
'https://www.artizanbath.co.uk/       ',
'https://www.huesalon.co.uk/          ',
'https://www.numberthreebath.com/     ',
'https://www.toniandguybath.com/      ',
'https://www.hairdressersbath.com/    ',
'https://www.no45hairdressing.co.uk/  ',
'https://www.davidmaxwellhairdressing.co.uk/',
'https://www.materialhair.co.uk/            ',
'https://www.figohairltd.co.uk/' ,
'https://www.melanie-giles.uk/ ',
'https://www.giuseppesofbath.co.uk/',
'https://www.zphairdressing.co.uk/ ',
'https://www.bhairdressing.co.uk/',
'https://www.russellbrookshairdressing.com/',
'https://www.looseendshair.co.uk/ ',
'https://www.vaughanhair.com/',
'https://www.cnv-hairdressing.co.uk/ ',
'https://www.nickbrainhairdressing.com/',
'https://www.thecourtyardhairconsultants.co.uk/',
'https://www.cornershairstudio.com/          ',
'https://www.tgolawski.wixsite.com/website/  ',
'https://www.hairzonebath.com/               ',
'https://www.heavenhair.co.uk/               ',
'https://www.perrycarson.com/                ',
'https://www.headsuphairdressersbath.co.uk/  ',
'https://www.russellbrookshairdressing.co.uk/',
'https://www.lunahaircare-bath.co.uk/        ',
'https://www.cherryblossomhairstudios.com/   ',
'https://www.monmouthsurgery.co.uk/          ',
'https://www.heartofbath.com/                ',
'https://www.widcombesurgery.nhs.uk/        ',
'https://www.pulteney.co.uk/                ',
'https://www.rushhillandwestonsurgery.co.uk/',
'https://www.newbridgesurgerybath.co.uk/    ',
'https://www.grosvenorplacesurgery.co.uk/   ',
'https://www.combedownsurgery.co.uk/        ',
'https://www.combedownsurgery.co.uk/        ',
'https://www.monmouthsurgery.co.uk/         ',
'https://www.heartofbath.com/               ',
'https://www.rushhillandwestonsurgery.co.uk/',
'https://www.newbridgesurgerybath.co.uk/    ',
'https://www.heartofbath.com/               ',
'https://www.stmichaelssurgery.co.uk/       ',
'https://www.rushhillandwestonsurgery.co.uk/team/doctors/ ',
'https://www.newbridgesurgerybath.co.uk/      ',
'https://www.awp.nhs.uk/                      ',
'https://www.bmihealthcare.co.uk/             ',
'https://www.ruh.nhs.uk/                      ',
'https://www.rnhrd.nhs.uk/                    ',
'https://www.bathcentreforpainservices.nhs.uk/',
'https://www.circlehealth.co.uk/bath/         ',
'https://www.royalcrescent.co.uk/             ',
'https://www.thebathpriory.co.uk/spa/the-garden-spa/ ',
'https://www.thermaebathspa.com/ ',
'https://www.golden-spa.co.uk/   ',
'https://www.thermaebathspa.com/ ',
'https://www.karenfreed.com/     ',
'https://www.resultsbodymind.co.uk/the-pod/',
'https://www.thebathmassagecompany.com/    ',
'https://www.bathtouchthaimassagespa.co.uk/',
'https://www.naturaltouchbath.co.uk/ ',
'https://www.uk.lush.com/shop/bath/  ',
'https://www.thesoulspa.co.uk/       ',
'https://www.bathosteopath.co.uk/    ',
'https://www.littlelab.co.uk/        ',
'https://www.duchessbeauty.co.uk/    ',
'https://www.frontlinestyle.co.uk/   ',
'https://www.saccobeauty.com/        ',
'https://www.allaboutyouinbath.com/  ',
'https://www.beautyatnumber32.co.uk/ ',
'https://www.bathbeautycentre.co.uk/ ',
'https://www.wisterialaneuk.com/     ',
'https://www.mystique-of-bath.co.uk/ ',
'https://www.beyondbeautybath.com/   ',
'https://www.planetbeautybath.co.uk/ ',
'https://www.mkbeautybath.co.uk/     ',
'https://www.sj-beauty.com/  ',
'https://www.dappa.co.uk/    ',
'https://www.lebarbier.co.uk/',
'https://www.starturkishbarber.wixsite.com/home/',
'https://www.blacksailsbarbershop.co.uk/        ',
'https://www.akbarberbath.nearcut.com/          ',
'https://www.hackettsbath.co.uk/                ',
'https://www.wolfbarbers.com/                   ',
'https://www.dylansmodabarbers.com/             ',
'https://www.headsupbarbersbath.co.uk/          ',
'https://www.fineanddandybarbers.com/           ',
'https://www.theguildhallbarbershop.nearcut.com/',
'https://www.holburne.org/           ',
'https://www.no1royalcrescent.org.uk/',
'https://www.americanmuseum.org/     ',
'https://www.herschelmuseum.org.uk/  ',
'https://www.bath-at-work.org.uk/    ',
'https://www.janeausten.co.uk/       ',
'https://www.sallylunns.co.uk/       ',
'https://www.bathpostalmuseum.co.uk/ ',
'https://www.oldtheatreroyal.com/    ',
'https://www.bathaquaglass.com/      ',
'https://www.fashionmuseum.co.uk/    ',
'https://www.museumofbatharchitecture.org.uk/',
'https://www.victoriagal.org.uk/       ',
'https://www.meaa.org.uk/              ',
'https://www.beckfordstower.org.uk/    ',
'https://www.museumofbathstone.org/    ',
'https://www.bathmedicalmuseum.org/    ',
'https://www.theatreroyal.org.uk/      ',
'https://www.missiontheatre.co.uk/     ',
'https://www.rondotheatre.co.uk/       ',
'https://www.tivolicinemas.com/        ',
'https://www.odeon.co.uk/cinemas/bath/?',
'https://www.picturehouses.com/cinema/little-theatre-cinema/',
'https://www.bathkingsmead.co.uk/                           ',
'https://www.beauxartsbath.co.uk/                           ',
'https://www.artgallerysw.co.uk/bath-art-expo/              ',
'https://www.whitewallgalleries.com/locate/bath/            ',
'https://www.44ad.net/            ',
'https://www.castlefineart.com/   ',
'https://www.artsalon.co.uk/      ',
'https://www.benhughesart.co.uk/  ',
'https://www.bathartgallery.co.uk/',
'https://www.bathartfair.co.uk/   ',
'https://www.nickcudworth.co.uk/  ',
'https://www.edgearts.org/        ',
'https://www.rostragallery.co.uk/ ',
'https://www.8hollandstreet.com/  ',
'https://www.galleryninebath.com/ ',
'https://www.axlearts.com/        ',
'https://www.pitch26.com/         ',
'https://www.adamgallery.com/bath/',
'https://www.chapelarts.org/      ',
'https://www.lanehousearts.co.uk/index.html/ ',
'https://www.francisgallery.co/              ',
'https://www.modernartbuyer.com/             ',
'https://www.rosegalleries.co.uk/            ',
'https://www.bathartistprintmakers.co.uk/    ',
'https://www.articulatebath.co/              ',

]